import NavbarWithData from "@/components/navbar/navbar-with-data";

export const metadata = {
  title: "Privacy Policy | Aiko Cricket",
  description: "Privacy policy for Aiko Cricket.",
};

export default function PrivacyPage() {
  const showAllLanguages = process.env.SHOW_ALL_LANGUAGES === "true";
  const authAuth0Id = process.env.AUTH_AUTH0_ID || "";
  const auth0Issuer = process.env.AUTH0_ISSUER || "";

  return (
    <>
      <NavbarWithData
        showAllLanguages={showAllLanguages}
        AUTH_AUTH0_ID={authAuth0Id}
        AUTH0_ISSUER={auth0Issuer}
      />
      <div className="min-h-screen bg-background">
        <div className="container mx-auto px-4 sm:px-6 py-10 max-w-4xl">
          <div className="rounded-2xl border bg-card/60 backdrop-blur-sm shadow-sm overflow-hidden">
            <div className="px-6 sm:px-8 py-8 border-b bg-linear-to-b from-muted/40 to-transparent">
              <h1 className="text-3xl sm:text-4xl font-bold tracking-tight">Privacy Policy</h1>
            </div>

            <div className="px-6 sm:px-8 py-8">
              <div className="space-y-6 text-sm sm:text-base leading-7 text-foreground/90">
                <p>
                  The website at <span className="font-semibold">www.aiko.cricket</span> (the{" "}
                  <span className="font-semibold">Website</span>) is owned and operated by{" "}
                  <span className="font-semibold">Aiko Inc Limited</span> (<span className="font-semibold">AIL</span>),
                  a company registered in England &amp; Wales under registration no.{" "}
                  <span className="font-semibold">16358577</span>.
                </p>

                <p>
                  AIL is committed to safeguarding the information that you provide to us. The following
                  privacy policy will explain how we will use and protect the information that you provide
                  to us.
                </p>

                <p>
                  By registering as a subscriber or visiting this Website, you consent to the collection,
                  use and transfer of your information under the terms of this policy. The Website
                  contains links to third party sites which are not subject to this privacy policy. Please
                  read the privacy policies of any such site as appropriate.
                </p>

                <section className="space-y-3">
                  <h2 className="text-xl sm:text-2xl font-semibold tracking-tight">Collection of Information</h2>
                  <p>
                    Some limited personal information is collected on the Website on behalf of AIL and its
                    group companies.
                  </p>

                  <p>We may collect personally identifiable information about you through:</p>
                  <ul className="list-disc pl-6 space-y-1 text-foreground/85">
                    <li>
                      the sign up process when you purchase or subscribe to any of our products or services;
                    </li>
                    <li>messages/comments you post to the Website,</li>
                    <li>emails, email attachments or other communications you send to us;</li>
                    <li>the provision of your details to us either online or offline</li>
                  </ul>

                  <p>Examples of data we will collect may include:</p>
                  <ul className="list-disc pl-6 space-y-1 text-foreground/85">
                    <li>Name</li>
                    <li>Job title</li>
                    <li>Company name</li>
                    <li>Company address, phone and fax number</li>
                    <li>Email address</li>
                    <li>Market research data such as usage patterns</li>
                    <li>Information regarding the use of our website and services</li>
                  </ul>

                  <p>
                    The majority of this data is not personal data and cannot be used to identify an
                    individual person.
                  </p>

                  <p>
                    Payment details, such as credit card information, are not collected by or accessible
                    to AIL. This service is strictly the responsibility of the payment solution provider.
                  </p>

                  <p>
                    We also collect information about your visit to the Website including the website that
                    referred you to us and, in some instances, the websites you visit after the Website.
                    When you log on as a subscriber, we may pass cookies to your computer.
                  </p>

                  <p>
                    Advertisements you see on the Website may have been generated by third parties. Third
                    parties may generate their own cookies, for example, to track how many times a user has
                    clicked on an advertisement. Third parties cannot access personal information held on
                    you by AIL.
                  </p>

                  <p>
                    AIL has taken appropriate measures to safeguard the data of our subscribers and users.
                    This data may be transferred outside AIL to data processors. These data processors can
                    act only according to our instructions. At all times, AIL remains the data controller.
                  </p>
                </section>

                <section className="space-y-3">
                  <h2 className="text-xl sm:text-2xl font-semibold tracking-tight">Transfer of Data</h2>
                  <p>
                    Certain AIL servers are located in the United States of America and by registering on
                    the Website you consent to the transfer of your information to countries outside the
                    European Economic Area (EEA) and transmission of data on an international basis.
                  </p>
                </section>

                <section className="space-y-3">
                  <h2 className="text-xl sm:text-2xl font-semibold tracking-tight">Use of your Information</h2>
                  <p>
                    Your information will enable AIL to provide you with access to all parts of this Website
                    and to supply the services you have requested. It will also enable AIL to contact you
                    where necessary. AIL will also use and analyse the information collected so that AIL can
                    administer, support, improve and develop its business and services. If you register using
                    a corporate email address, we may share this information with representatives of your
                    company for the purposes of administering your account.
                  </p>

                  <p>AIL might use your information in the following ways:</p>
                  <ul className="list-disc pl-6 space-y-1 text-foreground/85">
                    <li>to ask you for your views on the services offered;</li>
                    <li>
                      to notify you about important changes or developments to the Website or the services;
                    </li>
                    <li>
                      to send newsletters or other updates to you regarding any services or news that may be
                      relevant to you; and
                    </li>
                    <li>if the law requires us to do so.</li>
                  </ul>

                  <p>
                    By providing your personal data to us, you consent to us <br/>
                    (i) processing your personal
                    data in relation to the provision of our services<br/>
                    (ii) sharing aggregated non-
                    personally identifiable information with third parties.
                  </p>

                  <p>
                    Unless required or permitted to do so by law, AIL will not otherwise share, sell or
                    distribute any of the information you provide to AIL without your consent.
                  </p>

                  <p>
                    This privacy policy may be amended without notice to you. Your continued use of the
                    Website will mean that you accept these changes.
                  </p>
                </section>

                <div className="mt-2 rounded-xl border bg-muted/30 p-5">
                  <p className="m-0 text-foreground/90">
                    If you would like us to remove your personal data from our database, please email{" "}
                    <a
                      className="font-medium text-primary underline underline-offset-4 hover:opacity-90"
                      href="mailto:admin@aiko.inc"
                    >
                      admin@aiko.inc
                    </a>
                    .
                  </p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </>
  );
}
